#!/usr/bin/perl
use warnings;
use strict;
use IO::Socket;
use Time::HiRes 'usleep';

# Make an RGB checkerboard
my $host = '192.168.7.2:9999';

my $sock = IO::Socket::INET->new(
	PeerAddr => $host,
	Proto => 'udp',
) or die "Socket failed: $!\n";


my $width = 64;
my $height = 210;
my $offset = 0;

my $i = 0;

while (1)
{
	$offset++;
	my $s = chr(1);
	my $bright = 0x30;

	for(my $y = 0 ; $y < $height ; $y++)
	{
		for(my $x = 0; $x < $width ; $x++)
		{
			my $r = ($i % 7 == 0) ? $bright : 0;
			my $g = ($i % 7 == 1) ? $bright : 0;
			my $b = ($i % 7 == 2) ? $bright : 0;

			$s .= chr($r);
			$s .= chr($g);
			$s .= chr($b);
			$i++;
		}
	}

	$sock->send($s);
	usleep(80000);
	$i++;
}
