#!/bin/bash
# WTF device tree?  So much work, and you still don't set the pin
# direction?

gpio_output() {
	gpio=$1
	n=$2
	pin=`expr 32 \* $gpio + $n`
	echo "Exporting GPIO$gpio.$n: pin $pin"
	echo $pin > /sys/class/gpio/unexport
	echo $pin > /sys/class/gpio/export
	echo 0 > /sys/class/gpio/gpio$pin/value
	echo out > /sys/class/gpio/gpio$pin/direction
}

for pin in 2 3 4 5 7 12 13 14 15 20 22 23 26 27 30 31; do
	gpio_output 0 $pin
done

for pin in 12 13 14 15 16 17 18 19 28 29; do
	gpio_output 1 $pin
done

for pin in 1 2 3 4 5; do
	gpio_output 2 $pin
done

for pin in 16 19; do
	gpio_output 3 $pin
done
