#!/usr/bin/perl
use warnings;
use strict;

# Make a smooth gradient pattern

my $width = 10;
my $height = 32;

my $s = '1';
my $bright = 0x10;

for(my $y = 0 ; $y < $height ; $y++)
{
	for(my $x =0 ; $x < $width ; $x++)
	{
		my $r = $x * $bright / $width;
		#my $r = ($width - $x - 1) * $bright / $width;
		#my $g = ($width - $x - 1) * $bright / $width;
		my $g = 0;
		my $b = ($height - $y - 1) * $bright / $height;

		$s .= chr($r);
		$s .= chr($g);
		$s .= chr($b);
	}
}

print $s;
