#########
#
# Build the various network receiving tools
#
#
BIN-y += matrix-udp-rx
BIN-y += matrix-tcp-rx
BIN-y += opc-rx

matrix-udp-rx.srcs += matrix-udp-rx.c
matrix-tcp-rx.srcs += matrix-tcp-rx.c
opc-rx.srcs += opc-rx.c

include ../../Makefile.common

