
BINDIR = ../../bin/

FILES = bbb-network-setup \
	find-serial \
	install \
	ledscape.service \
	python-test \
	run-ledscape \
	run-videoplayer \
	twitter-scroller \
	videoplayer \
	videoplayer.service \
	run-menu

all: copy

copy:
	cp -f $(FILES) $(BINDIR)
