#!/bin/bash

function runmenu {
	bin/menu
	local status=$?

	if [ $status -eq 0 ]; then
		bin/bricks
	fi

	if [ $status -eq 1 ]; then
		bin/paddles
	fi

	if [ $status -eq 2 ]; then
		bin/invaders
	fi
}

while true
do
	runmenu
done

