#! /bin/sh
# /etc/init.d/LEDscape

### BEGIN INIT INFO
# Provides:          LEDscape
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run the LEDscape scuplture
# Description:       loads the correct DTS file and then the LEDscape 
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting LEDscape"
    # run application you want to start
    bash -c 'cd /home/ubuntu/LEDscape/; ./run_ledscape'
    ;;
  stop)
    echo "Stopping LEDscape"
    # kill application you want to stop
    killall matrix-test
    ;;
  *)
    echo "Usage: /etc/init.d/LEDscape {start|stop}"
    exit 1
    ;;
esac

exit 0
