BINDIR = ../../../bin/

FILES = blip2.wav \
	blip3.wav \
	blip4.wav \
	blip5.wav \
	startup.wav \
	Invaders.png \
	Menus.png

all: copy

copy:
	cp -f $(FILES) $(BINDIR)

clean:
	rm -rf $(BINDIR)*.wav
	rm -rf $(BINDIR)Invaders.png

