BINDIR = ../../../bin/

FILES = blip2.wav \
	blip3.wav \
	blip4.wav \
	blip5.wav \
	startup.wav \
	Invaders.png \
	Menus.png \
	invader_explosion.wav \
	ship_explosion.wav \
	invader_march1.wav \
	invader_march2.wav \
	invader_march3.wav \
	invader_march4.wav
	

all: copy

copy:
	cp -f $(FILES) $(BINDIR)

clean:
	rm -rf $(BINDIR)*.wav
	rm -rf $(BINDIR)Invaders.png

