#!/bin/sh
DIR="`dirname $0`"
cd "$DIR"

route add default gw 192.168.7.1
echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo >&2 "setting date"
ntpdate -s pool.ntp.org
date

echo >&2 "probing serial ports"
./find-serial
