#!/bin/sh
# Locate the serial ports and their serial numbers.
# This can then be used to map devices to positions in the matrix.

lsusb -v > /dev/null

for dev in `find /sys/devices/ -name '*ACM*' `;do
	DIR=`dirname $dev`
	TTY=`basename $dev`
	SERIAL=`cat $DIR/../../serial`
	echo "/dev/$TTY: $SERIAL"
done
