#########
#
# Build the various demos
#
#
BIN-n += fire
BIN-n += life
BIN-n += cube-life
BIN-y += matrix-test
BIN-y += identify

fire.srcs += fire.c
life.srcs += life.c
identify.srcs += identify.c
cube-life.srcs += cube-life.c
matrix-test.srcs += matrix-test.c

include ../../Makefile.common

