#########
#
# Build the various demos
#
#
TARGETS-y += $(BINDIR)/fire
TARGETS-y += $(BINDIR)/matrix-test
TARGETS-y += $(BINDIR)/life
TARGETS-y += $(BINDIR)/cube-life

include ../../Makefile.common

$(BINDIR)/fire: $(OBJDIR)/fire.o
$(BINDIR)/matrix-test: $(OBJDIR)/matrix-test.o
$(BINDIR)/life: $(OBJDIR)/life.o
$(BINDIR)/cube-life: $(OBJDIR)/cube-life.o
