#########
#
# Build the various demos
#
#
BIN-y += fire
BIN-y += life
BIN-y += cube-life
BIN-y += matrix-test

fire.srcs += fire.c
life.srcs += life.c
cube-life.srcs += cube-life.c
matrix-test.srcs += matrix-test.c

include ../../Makefile.common

